# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(290, 355)
        MainWindow.setMinimumSize(QtCore.QSize(290, 355))
        MainWindow.setMaximumSize(QtCore.QSize(290, 355))
        MainWindow.setBaseSize(QtCore.QSize(290, 355))
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 271, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setAccessibleName("")
        self.tab.setObjectName("tab")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(210, 7, 42, 22))
        self.spinBox.setStatusTip("")
        self.spinBox.setWhatsThis("")
        self.spinBox.setAutoFillBackground(False)
        self.spinBox.setWrapping(True)
        self.spinBox.setReadOnly(False)
        self.spinBox.setMinimum(4)
        self.spinBox.setMaximum(10)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_GenPass = QtWidgets.QPushButton(self.tab)
        self.pushButton_GenPass.setGeometry(QtCore.QRect(10, 60, 241, 23))
        self.pushButton_GenPass.setObjectName("pushButton_GenPass")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 16))
        self.label.setObjectName("label")
        self.pushButton_SaveFile_Pass = QtWidgets.QPushButton(self.tab)
        self.pushButton_SaveFile_Pass.setGeometry(QtCore.QRect(10, 270, 241, 23))
        self.pushButton_SaveFile_Pass.setObjectName("pushButton_SaveFile_Pass")
        self.pushButton_SaveFile_Pass.setDisabled(True)
        self.textEdit_PassList = QtWidgets.QTextEdit(self.tab)
        self.textEdit_PassList.setGeometry(QtCore.QRect(10, 90, 241, 171))
        self.textEdit_PassList.setReadOnly(True)
        self.textEdit_PassList.setObjectName("textEdit_PassList")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 35, 91, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_PassType = QtWidgets.QComboBox(self.tab)
        self.comboBox_PassType.setGeometry(QtCore.QRect(106, 30, 69, 22))
        self.comboBox_PassType.setObjectName("comboBox_PassType")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(12, 128, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_Key = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Key.setGeometry(QtCore.QRect(50, 124, 131, 20))
        self.lineEdit_Key.setObjectName("lineEdit_Key")
        self.pushButton_Shifr = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Shifr.setGeometry(QtCore.QRect(30, 150, 91, 23))
        self.pushButton_Shifr.setObjectName("pushButton_Shifr")
        self.pushButton_DeShifr = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_DeShifr.setGeometry(QtCore.QRect(150, 150, 91, 23))
        self.pushButton_DeShifr.setObjectName("pushButton_DeShifr")
        self.pushButton_SaveFile_Shifr = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_SaveFile_Shifr.setGeometry(QtCore.QRect(10, 270, 241, 23))
        self.pushButton_SaveFile_Shifr.setObjectName("pushButton_SaveFile_Shifr")
        self.pushButton_SaveFile_Shifr.setDisabled(True)
        self.textEdit_Text = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_Text.setGeometry(QtCore.QRect(10, 30, 241, 81))
        self.textEdit_Text.setObjectName("textEdit_Text")
        self.textEdit_Shifr = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_Shifr.setGeometry(QtCore.QRect(10, 180, 241, 81))
        self.textEdit_Shifr.setReadOnly(True)
        self.textEdit_Shifr.setObjectName("textEdit_Shifr")
        self.comboBox_shifrLang = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_shifrLang.setGeometry(QtCore.QRect(182, 123, 69, 22))
        self.comboBox_shifrLang.setObjectName("comboBox_shifrLang")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Гильфанов 612 3в."))
        self.pushButton_GenPass.setText(_translate("MainWindow", "Сгенерировать пароли"))
        self.label.setText(_translate("MainWindow", "Введите число символов в пароле:"))
        self.pushButton_SaveFile_Pass.setText(_translate("MainWindow", "Сохранить в файл"))
        self.label_4.setText(_translate("MainWindow", "Спец. символы:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Генератор паролей"))
        self.label_2.setText(_translate("MainWindow", "Фраза:"))
        self.label_3.setText(_translate("MainWindow", "Ключ:"))
        self.pushButton_Shifr.setText(_translate("MainWindow", "Шифровать"))
        self.pushButton_DeShifr.setText(_translate("MainWindow", "Дешифровать"))
        self.pushButton_SaveFile_Shifr.setText(_translate("MainWindow", "Сохранить в файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Шифр Виженера"))
